version: '3.4'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes: 
      - mongo_db:/data/db
  jstasks:
    image: jstasks
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongo_db://db_container:27017
      DB_NAME: js_task
      NAME: JS_ENV
    ports:
      - 4000:3000
    depends_on:
    - mongo_db

volumes:
  mongo_db: {}
