version: '3'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - '27017:27023'
    volumes: 
      - mongo_db:/data/db

  server:
    image: jstasks
    command: npm run server
    build: . 
    environment:
      NODE_ENV: development
      PORT: 3000
      REDIS_URL: redis:6379
      MONGODB_URI: mongodb://mongo_db:27017
      MONGODB_DB_NAME: js_task
      SECRET_KEY: Secret_key_9928
    ports:
      - 3000:3000
    depends_on:
      - mongo_db
      - redis

  worker:
    image: jstasks
    command: npm run worker
    deploy:
      replicas: 2
    build: . 
    environment:
      NODE_ENV: dev
      REDIS_URL: redis:6379
      MONGODB_URI: mongodb://mongo_db:27017
      MONGODB_DB_NAME: js_task
    depends_on:
      - mongo_db
      - redis

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mongo_db: {}
