version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes: 
      - mongo_db:/data/db

  jstasks:
    image: jstasks
    build: . 
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      MONGODB_DB_NAME: js_task
    ports:
      - 4000:3000
    depends_on:
    - mongo_db

volumes:
  mongo_db: {}
