apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: worker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      
      labels:
        io.kompose.service: worker
    spec:
      containers:
        - args:
            - npm
            - run
            - worker
          env:
            - name: MONGODB_DB_NAME
              value: js_task
            - name: MONGODB_URI
              value: mongodb://mongo-db:27017
            - name: NODE_ENV
              value: dev
            - name: REDIS_URL
              value: redis:6379
          image: jstasks
          imagePullPolicy: Never
          name: worker
          resources: {}
      restartPolicy: Always
status: {}
